Fix program flow
This makes all `exit 0` statements unnecessary and simplifies control
flow.

diff --git a/bin/armbian-config b/bin/armbian-config
--- a/bin/armbian-config
+++ b/bin/armbian-config
@@ -56,17 +56,13 @@ echo "Loaded Software helpers..." #| show_infobox ;
 source "$lib_dir/config.runtime.sh"
 echo "Loaded Runtime conditions..." #| show_infobox ;
 
-clear
-
 case "$1" in
-"--help")
-	if [[ -n "$2" ]]; then
-		see_cmd_list "$2"
-		echo ""
-		exit 0
-	fi
-
-	echo "Usage:  armbian-config --[option]
+    "--help")
+        if [[ -n "$2" ]]; then
+            see_cmd_list "$2"
+            echo ""
+        else
+            echo "Usage:  armbian-config --[option]
      Options:
      --help [category]   Use [category] to filter specific menu options.
      --cmd  [option]     Run a command from the menu (simple)
@@ -78,90 +74,91 @@ case "$1" in
      armbian-config --cmd help 
      armbian-config --api help
 "
-	exit 0
-	;;
-"--doc")
-	generate_readme
-	exit 0
-	;;
-"--cmd")
-	INPUTMODE="cmd"
-	shift
-	if [[ -z "$1" || "$1" == "help" ]]; then
-		see_cmd_list
-		exit 0
-	fi
+        fi
+    ;;
 
-	args=$(sanitize_input "$@")
-	execute_command "$args"
-	exit 0
-	;;
-"--api")
-	shift
-	if [[ -z "$1" || "$1" == "help" ]]; then
-		see_use
-		exit 0
-	fi
-	option="$1"
-	shift
-	args=$(sanitize_input "$@")
-	# echo -e "\"$option\" \"$args\""
-	"$option" "$args"
-	exit 0
-	;;
-"main=help" | "main=Help")
-	see_cli_legacy
-	echo ""
-	exit 0
-	;;
-"main="*)
-	declare -A main_map
-	main_map=(
-		# map name to menu category
-		["System"]="S"
-		["Software"]="I"
-		["Network"]="N"
-		["Localisation"]="L"
-	)
-	main_value="${1#main=}"
-	main_value="${main_map[$main_value]}"
+    "--doc")
+        generate_readme
+    ;;
 
-	if [ -z "$main_value" ]; then
-		echo "Error: Invalid List $1"
-		exit 1
-	fi
-	declare -A select_map
-	# map name to menu number
-	select_map=(
-		["Headers"]="04"
-		["Headers_install"]="04"
-		["Headers_remove"]="05"
-		["Firmware"]="06"
-		["Nightly"]="07"
-	)
-	select_value="${2#selection=}"
-	select_value="${select_map[$select_value]}"
-	if [ -z "$select_value" ]; then
-		echo "Error: Invalid Option $2"
-		exit 1
-	fi
-	echo "$main_value""$select_value"
-	execute_command "$main_value""$select_value"
-	exit 0
+    "--cmd")
+        INPUTMODE="cmd"
+        shift
+        case "$1" in
+            ""|"help")
+                see_cmd_list
+            ;;
+            *)
+                args=$(sanitize_input "$@")
+                execute_command "$args"
+            ;;
+        esac
+    ;;
+
+    "--api")
+        shift
+        case "$1" in
+            ""|"help")
+                see_use
+            ;;
+            *)
+                option="$1"
+                shift
+                args=$(sanitize_input "$@")
+                # echo -e "\"$option\" \"$args\""
+                "$option" "$args"
+            ;;
+        esac
 	;;
+
+    "main=help" | "main=Help")
+        see_cli_legacy
+        echo ""
+	;;
+
+    "main="*)
+        declare -A main_map
+        main_map=(
+            # map name to menu category
+            ["System"]="S"
+            ["Software"]="I"
+            ["Network"]="N"
+            ["Localisation"]="L"
+        )
+        main_value="${1#main=}"
+        main_value="${main_map[$main_value]}"
+
+        if [ -z "$main_value" ]; then
+            echo "Error: Invalid List $1"
+            exit 1
+        fi
+        declare -A select_map
+        # map name to menu number
+        select_map=(
+            ["Headers"]="04"
+            ["Headers_install"]="04"
+            ["Headers_remove"]="05"
+            ["Firmware"]="06"
+            ["Nightly"]="07"
+        )
+        select_value="${2#selection=}"
+        select_value="${select_map[$select_value]}"
+        if [ -z "$select_value" ]; then
+            echo "Error: Invalid Option $2"
+            exit 1
+        fi
+        echo "$main_value""$select_value"
+        execute_command "$main_value""$select_value"
+	;;
+
+    *)
+        # Generate the top menu with the modified Object data
+        set_colors 4
+        generate_top_menu "$json_data"
+
+        # Show about this tool on exit
+        about_armbian_configng
+    ;;
 esac
-
-
-#
-# Generate the top menu with the modified Object data
-set_colors 4
-generate_top_menu "$json_data"
-
-#
-# Exit the script with a success status code
-
-#
-# Show about this tool on exit
-about_armbian_configng
 
 exit 0
