restoring accessibility

diff --git a/bin/armbian-configng b/bin/armbian-configng
--- a/bin/armbian-configng
+++ b/bin/armbian-configng
@@ -65,21 +65,23 @@ elif command -v dialog &> /dev/null; then
     dialogue="dialog"
 else
     echo "TUI not found"
-    echo "Warning: Using fallback TUI"
-    sleep 1
-    clear && generate_read
+    echo "try -t for text based interface"
+    # WIP: Add a fallback TUI
+    #echo "Warning: Using fallback TUI"
+    #sleep 1
+    #clear && generate_read
 fi
 
-source "$libpath/functionsng.sh"
 if [ -f "$libpath/documents.sh" ]; then
     source "$libpath/documents.sh"
 fi
+
+# load the group functions
 for file in "$libpath"/*/*.sh; do
     source "$file"
 done
 
 #
-# mapfile -t categories < <(ls -d "$libpath"/* )
 mapfile -t categories < <(find "$libpath"/* -type d)
 declare -A functions
 
@@ -90,21 +92,17 @@ for category in "${categories[@]}"; do
     if [[ -f "$category_file" ]]; then
         category_description=$(grep -oP "(?<=# @description ).*" "$category_file")
     fi
-
     for file in "$category"/*.sh; do
-        description=""
+        description=$(grep -oP "(?<=# @description ).*" "$file")
+        options=$(grep -oP "(?<=# @options ).*" "$file")
         while IFS= read -r line; do
-            if [[ $line =~ ^#\ @description\ (.*)$ ]]; then
-                description="${BASH_REMATCH[1]}"
-            elif [[ $line =~ ^function\ (.*::.*)\(\)\{$ ]]; then
-                # END: be15d9bcejpp
+            if [[ $line =~ ^function\ (.*::.*)\(\)\{$ ]]; then
                 function_name="${BASH_REMATCH[1]}"
                 key="$category_name:${file##*/}:${function_name}"
                 functions["$key,function_name"]=$(echo "$function_name" | sed 's/.*:://')
                 functions["$key,group_name"]=$(echo "$function_name" | sed 's/::.*//')
                 functions["$key,description"]=$description
-            elif [[ $line =~ ^#\ @options\ (.*)$ ]]; then
-                functions["$key,options"]="${BASH_REMATCH[1]}"
+                IFS= read -r functions["$key,options"] <<< "$options"
             fi
         done < "$file"
         functions["$key,category"]=$category_name
@@ -112,20 +110,174 @@ for category in "${categories[@]}"; do
     done
 done
 
+###############################################################################################
+###############################################################################################
 
-#
+# This function is used to generate a text-based user interface (TUI) for navigating the menus.
+generate_tui() {
+    local options=()
+    local i=0
+    declare -A categories_array
+    local help_index=-1
+
+    for category in "${categories[@]}"; do
+        local category_name="${category##*/}"
+        local category_description=""
+        local category_file="$category/readme.md"
+
+        if [[ -f "$category_file" ]]; then
+            category_description=$(grep -oP "(?<=# @description ).*" "$category_file")
+        fi
+
+        if [[ "$category_name" == "help" ]]; then
+            help_index=$i
+        else
+            categories_array["$i"]="$category_name"
+            description_array["$i"]="$category_description"
+            options+=("$i" "$(printf '%-7s - %-8s' "${categories_array[$i]}" "${description_array[$i]}")")
+            ((++i))
+        fi
+    done
+
+    # Add the help category if it exists
+    if [[ $help_index -ne -1 ]]; then
+        categories_array["$i"]="help"
+        description_array["$i"]="Documentation, support, sources"
+        options+=("$i" "$(printf '%-7s - %-8s' "${categories_array[$i]}" "${description_array[$i]}")")
+        ((++i))
+    fi
+
+    [[ -f /sbin/armbian-config ]] && options+=("$i" "$(printf '%-7s - %-8s' "Legacy" "Run Legacy configuration")") ; ((++i)) ;
+    [[ ! -d "$libpath/help" ]] && options+=("$i" "$(printf '%-7s - %-8s' "Help" "Documentation, support, sources")") ; ((++i)) ;
+
+    local choice
+    choice=$($dialogue --menu "Select a category:" 0 0 9 "${options[@]}" 3>&1 1>&2 2>&3)
+    
+    if [[ -n $choice ]]; then
+        if ((choice == "$i - 1")); then
+            generate_help ;
+            echo "" ;
+            generate_list_cli ; 
+            exit 0 ;
+        elif ((choice == "$i - 2")); then
+            armbian-config
+            exit ;
+        else
+            generate_sub_tui "${categories_array[$choice]}"
+        fi
+    fi
+}
+
+# This function is used to generate a text-based user interface (TUI) for navigating the menus.
+generate_sub_tui() {
+    local category="$1"
+    local options=()
+    local i=0
+    declare -A functions_array
+    for file in "$libpath/$category"/*.sh; do
+        mapfile -t functions_in_file < <(grep -oP '(?<=function\s)\w+::\w+' "$file")
+        for function in "${functions_in_file[@]}"; do
+            key="${category##*/}:${file##*/}:${function}"
+            functions_array["$i"]="$function"
+            options+=("$i" "${functions["$key,function_name"]} - ${functions["$key,description"]}")
+            ((++i))
+        done
+    done
+
+    local choice
+    
+    choice=$($dialogue --menu "Select a function:" 0 0 9 "${options[@]}" 3>&1 1>&2 2>&3)
+    
+    if [[ -n $choice ]]; then
+        generate_action "${functions_array[$choice]}"
+    fi
+
+}
+
+# This function is used to generate a whiptail/dialog text-based user interface (TUI) for navigating the menus.
+generate_action() {
+    local function_name="$1"
+            ${function_name}
+}
+
+# This function is used to generate a bash text-based user interface (TUI) for navigating the menus.
+generate_read() {
+    echo
+    echo "Please select an action:"
+    echo
+    # Initialize an empty array to store the function keys
+    declare -a function_keys
+
+    # Loop through each key in the functions array
+    local i=1
+    local current_category=""
+    for key in "${!functions[@]}"; do
+        if [[ $key == *",function_name" ]]; then
+            # Add the key to the function_keys array
+            function_keys[i]="${key%,function_name}"
+
+            # Check if the category has changed and display it if so
+            local category="${functions["${function_keys[i]},category"]}" # < editor"
+            if [[ "$category" != "$current_category" ]]; then
+                echo "Category: $category"
+                current_category="$category"
+            fi
+
+            # Display the function and its description as an option in the menu
+            echo "  $i. ${functions["${function_keys[i]},group_name"]} ${functions[$key]}  - ${functions["${function_keys[i]},description"]}" #" < for my editor
+            ((i++))
+        fi
+    done
+
+    echo
+    echo "$i. Show help"
+    ((i++))
+    echo "$i. Exit"
+
+    read -p "Enter your choice: " choice
+
+    if ((choice == i-1)); then
+        generate_help ; 
+    elif ((choice == i)); then
+        exit 0
+    elif ((choice >= 1 && choice <= ${#function_keys[@]})); then
+        # Call the selected function using variable indirection
+        eval "${functions["${function_keys[choice]},group_name"]}::${functions["${function_keys[choice]},function_name"]}" #" < for my editor
+    else
+        echo "Invalid choice"
+    fi
+}
+
+# This function is used to parse the action name and return the full function name.
+parse_action() {
+    local group=$1
+    local action=$2
+
+    # Construct the full function name
+    local function_name="${group}::${action}"
+
+    # Check if the function exists
+    if declare -f "$function_name" > /dev/null; then
+        # Return the function name
+        echo "$function_name"
+    else
+        echo "Error: Unknown action '$action' for group '$group'"
+        return 1
+    fi
+}
+###############################################################################################
 # WIP: Check arguments for no flag options
 # armbian-config --help
 # Change to BASH: /usr/sbin/armbian-config main=System selection=BASH
 handle_no_flag(){
-if [[ "$1" == *"="* ]]; then
-    IFS='=' read -r key value <<< "$1"
-    function_name=$(parse_action "$key" "$value")
-    # Call the function using variable indirection
-    ${function_name}
-elif [[ "$1" == "help"* ]]; then
-    generate_list_cli
-fi
+    if [[ "$1" == *"="* ]]; then
+        IFS='=' read -r key value <<< "$1"
+        function_name=$(parse_action "$key" "$value")
+        # Call the function using variable indirection
+        ${function_name}
+    elif [[ "$1" == "help"* ]]; then
+        generate_list_cli
+    fi
 }
 
 #
